### ISSUE TITLE
Remove console.log

### ISSUE THREAD

**Issue by adubbs** [ritz078/ngEmoticons#4]
Thanks so much for putting this together :wink: 

It's working great for me, but I was wondering if it would make sense to remove the `console.log` here....https://github.com/ritz078/ngEmoticons/blob/master/src/ng-emoticons.js#L278?

**Comment by ritz078** [comment]
Thanks for reporting this . Has been solved now :smile:

**Comment by adubbs** [comment]
Awesome thanks @ritz078!
