### ISSUE TITLE
Bower package not updated

### ISSUE THREAD

**Issue by kWeglinski** [ritz078/ngEmoticons#6]
Hey mate,
You forgot to update line at bower!
its still "name": "ngEmoticons", which cannot resolve 

> bower ngEmoticons#2.0.0      ENOTFOUND Package ngEmoticons not found

with this:

> "ng-emoticons": "2.0.0" 

works perfectly. 

Have a nice day!

**Comment by ritz078** [comment]
Hey @kWeglinski . Thanks for informing. I have fixed this .However I would recommend you to use [ngEmbed](https://github.com/ritz078/ngEmbed) as it has more features and in future the development on ngEmoticons will stop.
